document.write('<table width="100%"  border="0" cellspacing="0" cellpadding="4">')
document.write('<tr>')
document.write('<td width="41%"><img src="images/iitlogo2.jpeg" width="245" height="65"></td>')
document.write('<td width="41%" align="right"></td>')
document.write('</tr>')
document.write('<tr >')
document.write('<td  height="1" colspan="2"><img src="images/spacer.gif" width="100%" height="2"></td>')
document.write('</tr>')
document.write('</table>')