document.write('<table width="250" border="0" cellspacing="0" cellpadding="0">')
document.write('<tr>')
document.write('<td width="1%"><img src="images/1.gif" alt="" width="16" height="57"></td>')
document.write('<td width="98%" background="images/2.gif" class="bigtitlered">Search MOM</td>')
document.write('<td width="1%"><img src="images/3.gif" alt="" width="15" height="57"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td background="images/8.gif"></td>')
document.write('<td bgcolor="#FFFFFF">')
document.write('<table width="100%" border="0" cellspacing="0" cellpadding="6">')
document.write('<tr>')
document.write('<td class="textblack">By ID</td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><label for="textfield"></label>')
document.write('<input name="textfield" type="text" class="textbox" id="textfield"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td class="textblack">By Owner</td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><input name="textfield2" type="text" class="textbox" id="textfield2"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td class="textblack">By Title</td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><input name="textfield3" type="text" class="textbox" id="textfield3"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td class="textblack">By Created Date</td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><input name="textfield4" type="text" class="textbox" id="textfield4"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td class="textblack">By Created B111y</td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><input name="textfield5" type="text" class="textbox" id="textfield5"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><input name="Button" type="button" class="butgrey" id="button" value="Search" onClick="location.href=../mom_list.html">')
document.write('<input name="button2" type="reset" class="butgrey" id="button2" value="Reset"></td>')
document.write('</tr>')
document.write('</table>')
document.write('</td>')
document.write('<td background="images/4.gif"></td>')
document.write('</tr>')
document.write('<tr>')
document.write('<td><img src="images/7.gif" alt="" width="16" height="17"></td>')
document.write('<td background="images/6.gif"></td>')
document.write('<td><img src="images/5.gif" alt="" width="15" height="17"></td>')
document.write('</tr>')
document.write('</table>')