document.write('<html>');
document.write('<head>');
/*document.write('<script type="text/javascript">');
document.write('function isNumberKey(evt)');
document.write('{');
document.write('var charCode = (evt.which) ? evt.which : event.keyCode');
document.write('if (charCode > 31 && (charCode < 48 || charCode > 57))');
document.write('return false;');
document.write('return true;');
document.write('}');
document.write('</script>');*/
document.write('<script>');
document.write('function assign(){');
document.write('document.getElementById("ButtonPressed").value="Search";');
//document.write('alert(document.getElementById("ButtonPressed").value);');
document.write('}');
document.write('</script>');
document.write('</head>');
document.write('<div>');
document.write('<table width="80%" border="0" cellspacing="0" cellpadding="6" align="center">');
document.write('<tr>');
document.write('<form  name="topPannel" id="topPannel" method="post" action="/MoM/MoMServlet" >');
document.write('<input type="hidden" name="search" value="search">');
document.write('<td class="textwhite" align="left">By Connection</td>');
document.write('<td class="textwhite" align="left">By MoM ID</td>');
document.write('<td class="textwhite" align="left">By Action Owner</td>');
document.write('<td class="textwhite" align="left">By Subject</td>');
document.write('<td class="textwhite" align="left">By Meeting Date</td>');
document.write('<td class="textwhite" align="left">By Attended by</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td align="left"><input name="ByConnection" type="text" class="textbox1" id="ByConnection" autocomplete="off"></td>');
document.write('<td align="left"><input name="ByMomid" type="text" class="textbox1" id="ByMomid" onkeypress="return isNumberKey(event);" autocomplete="off"></td>');
document.write('<td align="left"><input name="ByActionOwner" type="text" class="textbox1" id="ByActionOwner" autocomplete="off"/></td>');
document.write('<td align="left"><input name="BySubject" type="text" class="textbox1" id="BySubject" autocomplete="off"/></td>');
//document.write('<td align="left"><input name="ByMeetingDate" class="textbox1" type="text" id="ByMeetingDate" readonly/></td>');
document.write('<td align="left">');
document.write('<div class="example-container">');
document.write('<div>');
document.write('<input type="text" name="ByMeetingDate" id="ByMeetingDate" value="" class="textbox1" readonly/>');
//document.write(' <input type="text" name="ByMeetingTime" id="ByMeetingTime" value="" size="12" class="textbox1" readonly/>');
document.write('</div>');
document.write('<script>');
document.write('$("#ByMeetingDate").datepicker({ dateFormat: "dd-M-yy",maxDate: new Date,');
document.write('altField: "#ByMeetingTime",');
document.write('addSliderAccess: true,');
document.write('sliderAccessArgs: { touchonly: false }');
document.write('});');
document.write('</script>');
document.write('</div>');
document.write('<td align="left"><input name="ByAttendedBy" type="text" class="textbox1" id="ByAttendedBy" autocomplete="off"/></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="6" align="left"><input name="Button" type="submit" class="butgrey1" id="button" value="Search" onclick="assign();">&nbsp;');
document.write('<input type="hidden" name="ButtonPressed" id="ButtonPressed" value="">');
document.write('<input name="button2" type="reset" class="butgrey1" id="button2" value="Clear"></td>');

document.write('</tr>');

document.write('</table>');
document.write('</div>');
document.write('</form>');
document.write('</div> <!-- /login -->');
document.write('<!-- The tab on top -->');
document.write('<div class="tab">');
document.write('<ul class="login">');
document.write('<li class="left">&nbsp;</li>');
document.write('<li>Welcome '+GlobalLogindUser+'</li>');
document.write('<li class="sep">|</li>');
document.write('<li id="toggle">');
document.write('<a id="open" class="open" href="#">Search MoM</a>');
document.write('<a id="close" style="display: none;" class="close" href="#">Close Panel</a>');
document.write('</li>');
document.write('<li class="right">&nbsp;</li>');

document.write('</ul>');
document.write('</div> <!-- / top -->');
document.write('</html>');

